### ISSUE TITLE
Unsupported custom field type: com.atlassian.jira.plugin.system.customfieldtypes:multigrouppicker

### ISSUE THREAD

**Issue by logopk** [codescape/jira-multiple-subtasks#106]
Hi,

as mentioned in the user guide, I would like to request support for another custom field type: "com.atlassian.jira.plugin.system.customfieldtypes:multigrouppicker".

That would be extremly nice ;-).

Thank you

Peter

**Comment by codescape** [comment]
Thank you for your request. I will look into this custom field type for one of the next releases!

**Comment by codescape** [comment]
Hey @logopk, as you can see the feature is already implemented and will be shipped with the next release.

**Comment by logopk** [comment]
I have tested it and it works as expected! As usual "()" in the field name need to be escaped.
